# Generated by Django 4.0.4 on 2023-06-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0002_remove_photo_model_model_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='photoCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
