# Generated by Django 4.0.4 on 2023-06-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0003_model_photocount_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
