# Generated by Django 4.0.4 on 2023-06-22 09:24

import admini.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0005_photo_path_alter_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='admini.model'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=admini.models.getDynamicUploadPath),
        ),
    ]
